from pathlib import Path

index=Path('index.html')
text=index.read_text(encoding='utf-8')

def replace_once(old,new,label):
    global text
    c=text.count(old)
    if c!=1:
        raise SystemExit(f'{label}: expected 1 match, found {c}')
    text=text.replace(old,new,1)

def replace_section(start,end,replacement,label):
    global text
    a=text.find(start)
    if a<0: raise SystemExit(f'{label}: start not found')
    b=text.find(end,a)
    if b<0: raise SystemExit(f'{label}: end not found')
    text=text[:a]+replacement+text[b:]

replace_once("+' · 0.27.9';","+' · 0.28.0';",'version')
replace_once("settingsLocationCheck=0,geocodeQueue=Promise.resolve(),geocodeLastAt=0;","settingsLocationCheck=0,geocodeQueue=Promise.resolve(),geocodeLastAt=0,expandedLocationId=null,settingsLocationsOpen=false,settingsLocationOriginId=null;",'location ux state')
replace_once("destinationTimeWindowHours:2,geocoderBaseUrl:GEOCODER_DEFAULT_BASE}","destinationTimeWindowHours:2,geocoderBaseUrl:GEOCODER_DEFAULT_BASE,locationSortMode:'smart'}",'location sort default')

css=r'''
/* 0.28.0 — locatieoverzicht en compacte keuzevelden */
.location-sort{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:12px;padding:4px;border:1px solid var(--line);border-radius:12px;background:var(--card)}.location-sort button{min-height:34px;border:0;border-radius:8px;background:transparent;color:var(--muted);font-size:11px;font-weight:800;cursor:pointer}.location-sort button.active{background:var(--card2);color:var(--text)}.location-entry.expanded .location-swipe-surface .chev{transform:rotate(90deg)}.location-inline-details{margin:-3px 0 4px;padding:12px 12px 13px;border:1px solid var(--line);border-top:0;border-radius:0 0 12px 12px;background:var(--card)}.location-inline-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.location-inline-item{padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:#101722}.location-inline-item span,.location-inline-item strong{display:block}.location-inline-item span{font-size:9px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}.location-inline-item strong{margin-top:3px;font-size:12px;overflow-wrap:anywhere}.location-inline-address{margin-top:8px;padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:#101722;font-size:11px;line-height:1.4;color:var(--muted);overflow-wrap:anywhere}.location-choice-grid{display:grid;gap:7px}.location-choice-grid.type{grid-template-columns:repeat(5,minmax(0,1fr))}.location-choice-grid.share{grid-template-columns:repeat(3,minmax(0,1fr))}.location-choice{position:relative}.location-choice input{position:absolute;opacity:0;pointer-events:none}.location-choice span{display:flex;min-height:58px;flex-direction:column;align-items:center;justify-content:center;gap:4px;padding:7px 3px;border:1px solid var(--line);border-radius:11px;background:#101722;color:var(--muted);font-size:10px;font-weight:800;text-align:center;cursor:pointer}.location-choice .choice-icon{font-size:18px;line-height:1}.location-choice input:checked+span{border-color:var(--accent);background:rgba(77,163,255,.12);color:var(--text);box-shadow:inset 0 0 0 1px var(--accent)}.location-choice.type-home input:checked+span{border-color:var(--home);box-shadow:inset 0 0 0 1px var(--home)}.location-choice.type-work input:checked+span{border-color:var(--commute);box-shadow:inset 0 0 0 1px var(--commute)}.location-choice.type-business input:checked+span{border-color:var(--business);box-shadow:inset 0 0 0 1px var(--business)}.location-choice.type-private input:checked+span{border-color:var(--private);box-shadow:inset 0 0 0 1px var(--private)}.location-choice.type-other input:checked+span{border-color:var(--other);box-shadow:inset 0 0 0 1px var(--other)}@media(max-width:420px){.location-choice-grid.type{gap:4px}.location-choice span{padding-left:2px;padding-right:2px;font-size:9px}.location-inline-grid{grid-template-columns:1fr}}
'''
replace_once('\n</style>','\n'+css+'\n</style>','location ux css')

replace_once("else if(a==='trip-toggle'){if(el.dataset.suppressClick==='1'){delete el.dataset.suppressClick}else{const id=el.dataset.id||el.closest('[data-id]')?.dataset.id;expandedTripId=expandedTripId===id?null:id;render()}}else if(a==='edit-trip')", "else if(a==='trip-toggle'){if(el.dataset.suppressClick==='1'){delete el.dataset.suppressClick}else{const id=el.dataset.id||el.closest('[data-id]')?.dataset.id;expandedTripId=expandedTripId===id?null:id;render()}}else if(a==='location-toggle'){if(el.dataset.suppressClick==='1'){delete el.dataset.suppressClick}else{const id=el.dataset.id||el.closest('[data-id]')?.dataset.id;expandedLocationId=expandedLocationId===id?null:id;settingsLocationsOpen=true;refreshSettingsLocationList()}}else if(a==='location-sort'){data.settings.locationSortMode=el.dataset.mode==='alpha'?'alpha':'smart';settingsLocationsOpen=true;save();refreshSettingsLocationList()}else if(a==='edit-trip')",'location click actions')
replace_once("document.addEventListener('input',e=>{if(e.target.closest?.('#settingsForm'))autosaveSettings();", "document.addEventListener('toggle',e=>{if(e.target?.id==='settingsLocationsDetails')settingsLocationsOpen=e.target.open},true);\ndocument.addEventListener('input',e=>{if(e.target.closest?.('#settingsForm'))autosaveSettings();",'location accordion state')

start='function locationTypeClass(type){'
end='function locationQuickActionsHtml()'
replacement=r'''function locationTypeClass(type){return`location-type-${['home','work','business','private'].includes(type)?type:'other'}`}
function locationTypeIcon(type){return type==='home'?'🏠':type==='work'?'🧰':type==='business'?'🏢':type==='private'?'👤':'📍'}
function locationShareStatus(value){const v=['ask','always'].includes(value)?value:'never',label=v==='ask'?'Rit delen: vraag mij':v==='always'?'Rit delen: altijd tonen':'Rit delen: nooit';return`<span class="location-share-status ${v}" title="${attr(label)}" aria-label="${attr(label)}">↗</span>`}
function locationHasGps(l){return parseNum(l?.lat)!=null&&parseNum(l?.lng)!=null}
function locationLinkStatus(l){const hasAddress=!!String(l?.address||'').trim(),hasGps=locationHasGps(l);let cls='none',label='Adres en GPS ontbreken',icon='A·⌖';if(hasAddress&&hasGps){cls='complete';label='Adres en GPS gekoppeld';icon='A↔⌖'}else if(hasAddress){cls='address-only';label='Adres aanwezig · GPS kan worden aangevuld';icon='A→⌖'}else if(hasGps){cls='gps-only';label='GPS aanwezig · adres kan worden aangevuld';icon='⌖→A'}return`<span class="location-link-status ${cls}" title="${attr(label)}" aria-label="${attr(label)}">${icon}</span>`}
function locationStatusIcons(l){return`<div class="location-status-icons">${locationShareStatus(l.shareRide||'never')}${locationLinkStatus(l)}</div>`}
function locationSortMode(){return data.settings.locationSortMode==='alpha'?'alpha':'smart'}
function settingsMomentOrigin(){return data.locations.find(x=>x.id===settingsLocationOriginId)||data.lastEndpoint?.location||inferLast()?.location||null}
function locationMomentScore(l,origin,moment=new Date(),suggested=null){let score=(+l.useCount||0)*.15;if(origin&&sameLoc(l,origin))score-=100;if(suggested&&sameLoc(l,suggested))score+=60;if(origin?.type==='home'&&l.type==='work')score+=18;if(origin?.type==='work'&&l.type==='home')score+=18;if((isConfiguredPrivateDay(moment)||isConfiguredPrivateTime(moment))&&l.type==='private')score+=12;const now=new Date(moment),nowMin=now.getHours()*60+now.getMinutes(),weekday=now.getDay(),weekend=weekday===0||weekday===6,windowMin=destinationTimeWindowHours()*60,dayMs=86400000;const relevant=sortedTrips().filter(t=>sameLoc(t.destination,l)&&(!origin||sameLoc(t.origin,origin))).slice(0,60);for(const t of relevant){const d=new Date(t.departureTime);if(Number.isNaN(d.getTime()))continue;const age=Math.max(0,(now-d)/dayMs),thenMin=d.getHours()*60+d.getMinutes(),raw=Math.abs(thenMin-nowMin),diff=Math.min(raw,1440-raw);score+=Math.max(0,7-age*.12);if(d.getDay()===weekday)score+=4;if(((d.getDay()===0||d.getDay()===6)===weekend))score+=2;if(diff<=windowMin)score+=8*Math.max(0,1-diff/windowMin)}return score}
function sortedSettingsLocations(){const arr=[...data.locations];if(locationSortMode()==='alpha')return arr.sort((a,b)=>a.name.localeCompare(b.name,'nl',{sensitivity:'base'}));const origin=settingsMomentOrigin(),moment=new Date(),suggested=origin?suggestDestination(origin,moment).location:null;return arr.sort((a,b)=>locationMomentScore(b,origin,moment,suggested)-locationMomentScore(a,origin,moment,suggested)||a.name.localeCompare(b.name,'nl',{sensitivity:'base'}))}
function locationSortControls(){const mode=locationSortMode();return`<div class="location-sort" aria-label="Locaties sorteren"><button type="button" class="${mode==='smart'?'active':''}" data-action="location-sort" data-mode="smart">◎ Logisch</button><button type="button" class="${mode==='alpha'?'active':''}" data-action="location-sort" data-mode="alpha">A–Z Naam</button></div>`}
function locationInlineDetails(l){const gps=coords(l)||'Niet vastgelegd',address=String(l.address||'').trim()||'Niet vastgelegd';return`<div class="location-inline-details"><div class="location-inline-grid"><div class="location-inline-item"><span>Type</span><strong>${locationTypeIcon(l.type)} ${esc(typeLabel(l.type))}</strong></div><div class="location-inline-item"><span>Rit delen</span><strong>${esc(shareRideLabel(l.shareRide||'never'))}</strong></div><div class="location-inline-item"><span>GPS</span><strong>${esc(gps)}</strong></div><div class="location-inline-item"><span>Gebruikt</span><strong>${odo(l.useCount||0)}×</strong></div></div><div class="location-inline-address"><strong>Adres</strong><br>${esc(address)}</div></div>`}
function locationSwipeRow(l){const expanded=expandedLocationId===l.id;return`<div class="location-entry ${expanded?'expanded':''}" data-id="${l.id}"><div class="swipe-row location-swipe-row" data-swipe-kind="location" data-id="${l.id}">${swipeActions('location',l.id)}<div class="swipe-surface location-item location-swipe-surface ${locationTypeClass(l.type)}" data-action="location-toggle" data-id="${l.id}"><div class="location-main"><strong>${esc(l.name)}</strong><small>${esc(l.address||coords(l)||'Geen adres/GPS')}</small></div>${locationStatusIcons(l)}<div class="chev">›</div></div></div>${expanded?locationInlineDetails(l):''}</div>`}
function settingsLocations(){const arr=sortedSettingsLocations();return`${locationSortControls()}${arr.length?`<div class="location-list">${arr.map(locationSwipeRow).join('')}</div>`:'<div class="hint" style="margin-top:12px">Nog geen locaties opgeslagen.</div>'}`}
function refreshSettingsLocationList(){const wrap=document.getElementById('settingsLocationListWrap');if(wrap)wrap.innerHTML=settingsLocations()}
'''
replace_section(start,end,replacement,'location overview functions')

refresh=r'''async function refreshSettingsLocationState(){const token=++settingsLocationCheck,wrap=document.getElementById('locationQuickActions'),status=document.getElementById('locationCurrentStatus');if(!wrap||!status||view!=='settings')return;if(!navigator.geolocation){status.textContent='GPS is niet beschikbaar op dit apparaat.';return}try{const g=await getPosition();if(token!==settingsLocationCheck||view!=='settings')return;const currentWrap=document.getElementById('locationQuickActions'),currentStatus=document.getElementById('locationCurrentStatus');if(!currentWrap||!currentStatus)return;const match=matches(g)[0]||null;settingsLocationOriginId=match?.location?.id||null;if(match){currentWrap.classList.add('known');currentWrap.innerHTML=`<button type="button" class="btn secondary current-known" data-action="edit-location" data-id="${match.location.id}">✓ Bekend</button><button type="button" class="btn secondary" data-action="add-location">Nieuwe locatie +</button>`;currentStatus.className='location-current-status known';currentStatus.textContent=`Huidige locatie is al opgeslagen als ${match.location.name}.`}else{currentWrap.classList.remove('known');currentStatus.className='location-current-status';currentStatus.textContent='Huidige locatie is nog niet opgeslagen.'}if(locationSortMode()==='smart')refreshSettingsLocationList()}catch(e){if(token!==settingsLocationCheck||view!=='settings')return;settingsLocationOriginId=null;const currentStatus=document.getElementById('locationCurrentStatus');if(currentStatus){currentStatus.className='location-current-status';currentStatus.textContent='Huidige locatie kon niet worden gecontroleerd.'}if(locationSortMode()==='smart')refreshSettingsLocationList()}}
'''
replace_section('async function refreshSettingsLocationState(){','function renderSettings(){',refresh,'refresh location state')

old_details='<details class="accordion"><summary><span class="accordion-title"><strong>Locaties</strong><small>${data.locations.length} opgeslagen</small></span><span class="accordion-arrow">›</span></summary><div class="accordion-body">${locationQuickActionsHtml()}${settingsLocations()}</div></details>'
new_details='<details id="settingsLocationsDetails" class="accordion" ${settingsLocationsOpen?\'open\':\'\'}><summary><span class="accordion-title"><strong>Locaties</strong><small>${data.locations.length} opgeslagen</small></span><span class="accordion-arrow">›</span></summary><div class="accordion-body">${locationQuickActionsHtml()}<div id="settingsLocationListWrap">${settingsLocations()}</div></div></details>'
replace_once(old_details,new_details,'locations accordion')

form_funcs=r'''function locationTypeOption(value,icon,label,current){return`<label class="location-choice type-${value}"><input type="radio" name="type" value="${value}" ${current===value?'checked':''} required><span><b class="choice-icon">${icon}</b>${label}</span></label>`}
function locationShareOption(value,icon,label,current){return`<label class="location-choice"><input type="radio" name="shareRide" value="${value}" ${current===value?'checked':''} required><span><b class="choice-icon">${icon}</b>${label}</span></label>`}
function openLocation(id=null,current=false){settingsLocationsOpen=true;const l=id?data.locations.find(x=>x.id===id):null,build=g=>{openModal(`<div class="modal-head"><h2>${l?'Locatie wijzigen':'Locatie toevoegen'}</h2><button class="close" data-action="close">×</button></div><form id="locationForm" onsubmit="return false"><input type="hidden" name="id" value="${l?.id||''}">${field('Naam','name',l?.name||'')}${field('Adres','address',l?.address||'')}<button type="button" class="btn secondary full" data-action="gps-location">Gebruik huidige GPS</button>${field('Latitude','lat',l?.lat??g?.lat??'','text')}${field('Longitude','lng',l?.lng??g?.lng??'','text')}<div class="location-link-hint"><strong>Adres ↔ GPS</strong><br>Alleen ontbrekende gegevens worden automatisch aangevuld. Bestaande waarden blijven staan. Huidige GPS overschrijft bewust alleen de coördinaten om ze nauwkeuriger te maken.</div><div class="osm-attribution">Adreszoeking via OpenStreetMap Nominatim · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap-bijdragers</a></div><div class="form-group"><label>Type</label><div class="location-choice-grid type">${locationTypeOption('home','🏠','Thuis',l?.type||'other')}${locationTypeOption('work','🧰','Werk',l?.type||'other')}${locationTypeOption('business','🏢','Zakelijk',l?.type||'other')}${locationTypeOption('private','👤','Privé',l?.type||'other')}${locationTypeOption('other','📍','Overig',l?.type||'other')}</div></div><div class="form-group"><label>Rit delen</label><div class="location-choice-grid share">${locationShareOption('never','⊘','Nooit',l?.shareRide||'never')}${locationShareOption('ask','?','Vraag mij',l?.shareRide||'never')}${locationShareOption('always','↗','Altijd',l?.shareRide||'never')}</div><div class="hint" style="margin-top:6px">Bij Vraag mij krijg je na vertrek een eenmalige vraag. Bij Altijd blijft Deel rit beschikbaar tijdens de actieve rit.</div></div><div class="hint">Vul minimaal naam, adres of GPS in.</div><div id="locationStatus" class="hint"></div><button type="button" class="btn full" data-action="save-location">Locatie opslaan</button></form>`);setTimeout(()=>autoCompleteLocationForm(),0)};if(current)getPosition().then(build).catch(e=>{toast(e.message);build(null)});else build(null)}
async function fillGps(){const f=document.getElementById('locationForm');if(!f)return;const g=await getPosition();f.elements.lat.value=(+g.lat).toFixed(6);f.elements.lng.value=(+g.lng).toFixed(6);setLocationStatus('GPS verfijnd met je huidige locatie.');await autoFillLocationFromGps();toast('GPS verfijnd met huidige locatie.')}
async function saveLocation(){const f=document.getElementById('locationForm');if(!f)throw new Error('Locatieformulier niet gevonden.');await autoCompleteLocationForm();const fd=new FormData(f),id=String(fd.get('id')||uid()),old=data.locations.find(x=>x.id===id),rawName=String(fd.get('name')||'').trim(),address=String(fd.get('address')||'').trim(),lat=parseNum(fd.get('lat')),lng=parseNum(fd.get('lng'));if((lat==null)!=(lng==null))throw new Error('Vul beide GPS-coördinaten in of laat beide leeg.');if(lat!=null&&Math.abs(lat)>90)throw new Error('Latitude is ongeldig.');if(lng!=null&&Math.abs(lng)>180)throw new Error('Longitude is ongeldig.');if(!rawName&&!address&&lat==null)throw new Error('Vul minimaal naam, adres of GPS in.');const name=rawName||address||`Locatie ${lat.toFixed(5)}, ${lng.toFixed(5)}`,loc={id,name,address,lat,lng,type:String(fd.get('type')||'other'),shareRide:['ask','always'].includes(String(fd.get('shareRide')||''))?String(fd.get('shareRide')):'never',useCount:old?.useCount||0,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()},i=data.locations.findIndex(x=>x.id===id);if(i>=0)data.locations[i]=loc;else data.locations.push(loc);save();if(!JSON.parse(localStorage.getItem(KEY)||'{}').locations?.some(x=>x.id===id))throw new Error('Locatie niet teruggevonden in opslag.');expandedLocationId=id;settingsLocationsOpen=true;closeModal();render();toast('Locatie opgeslagen: '+name)}
'''
replace_section('function openLocation(id=null,current=false){','function deleteLocation(id){',form_funcs,'location edit form')
replace_once("function deleteLocation(id){if(!confirm('Locatie verwijderen? Bestaande ritten blijven intact.'))return;data.locations=data.locations.filter(x=>x.id!==id);save();render();toast('Locatie verwijderd.')}","function deleteLocation(id){if(!confirm('Locatie verwijderen? Bestaande ritten blijven intact.'))return;data.locations=data.locations.filter(x=>x.id!==id);if(expandedLocationId===id)expandedLocationId=null;settingsLocationsOpen=true;save();render();toast('Locatie verwijderd.')}",'delete keeps locations open')

index.write_text(text,encoding='utf-8')
sw=Path('service-worker.js')
s=sw.read_text(encoding='utf-8')
if s.count("kmreg-shell-0.27.9")!=1: raise SystemExit('service worker version mismatch')
s=s.replace("kmreg-shell-0.27.9","kmreg-shell-0.28.0",1)
sw.write_text(s,encoding='utf-8')
script=text.split('<script>',1)[1].rsplit('</script>',1)[0]
Path('/tmp/kmreg-app.js').write_text(script,encoding='utf-8')
