from pathlib import Path

index = Path('index.html')
text = index.read_text(encoding='utf-8')

def replace_once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    text = text.replace(old, new, 1)

replace_once("+' · 0.27.8';", "+' · 0.27.9';", 'version')
replace_once("const KEY='kmreg-v4-data';", "const KEY='kmreg-v4-data',GEOCODE_CACHE_KEY='kmreg-geocode-cache-v1',GEOCODER_DEFAULT_BASE='https://nominatim.openstreetmap.org';", 'geocoder constants')
replace_once("destinationTimeWindowHours:2},locations", "destinationTimeWindowHours:2,geocoderBaseUrl:GEOCODER_DEFAULT_BASE},locations", 'default geocoder')
replace_once("settingsLocationCheck=0;", "settingsLocationCheck=0,geocodeQueue=Promise.resolve(),geocodeLastAt=0;", 'geocode state')

css = r'''
/* 0.27.9 — tokenloze adres/GPS-koppeling via Nominatim */
.location-status-icons{display:flex;flex:0 0 34px;flex-direction:column;align-items:center;gap:5px;margin-left:auto}.location-status-icons .location-share-status{margin-left:0}.location-link-status{display:inline-flex;align-items:center;justify-content:center;width:34px;height:22px;padding:0 3px;border:1px solid var(--line);border-radius:7px;color:var(--muted);font-size:9px;font-weight:850;letter-spacing:-.06em;line-height:1;white-space:nowrap}.location-link-status.complete{border-color:rgba(73,209,125,.45);color:var(--good);background:rgba(73,209,125,.08)}.location-link-status.address-only,.location-link-status.gps-only{border-color:rgba(255,189,74,.45);color:var(--warn);background:rgba(255,189,74,.07)}.location-link-status.none{opacity:.35}.location-link-hint{margin-top:7px;padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--muted);font-size:11px;line-height:1.4}.location-link-hint strong{color:var(--text)}.osm-attribution{margin-top:7px;font-size:10px;color:var(--muted)}.osm-attribution a{color:var(--muted)}
'''
replace_once('\n</style>', '\n' + css + '\n</style>', 'geocoding css')

replace_once("else if(a==='save-location')saveLocation();", "else if(a==='save-location')await saveLocation();", 'await location save')
replace_once("if(e.target.id==='arrivalDestination')refreshArrivalEstimates()});", "if(e.target.id==='arrivalDestination')refreshArrivalEstimates();if(e.target.closest?.('#locationForm')){if(e.target.name==='address')await autoFillLocationFromAddress();if(e.target.name==='lat'||e.target.name==='lng')await autoFillLocationFromGps()}});", 'location change geocoding')

old_rows = r'''function locationTypeClass(type){return`location-type-${['home','work','business','private'].includes(type)?type:'other'}`}
function locationShareStatus(value){const v=['ask','always'].includes(value)?value:'never',label=v==='ask'?'Rit delen: vraag mij':v==='always'?'Rit delen: altijd tonen':'Rit delen: nooit';return`<span class="location-share-status ${v}" title="${attr(label)}" aria-label="${attr(label)}">↗</span>`}
function locationSwipeRow(l){return`<div class="swipe-row location-swipe-row" data-swipe-kind="location" data-id="${l.id}">${swipeActions('location',l.id)}<div class="swipe-surface location-item location-swipe-surface ${locationTypeClass(l.type)}" data-action="edit-location" data-id="${l.id}"><div class="location-main"><strong>${esc(l.name)}</strong><small>${esc(l.address||coords(l)||'Geen adres/GPS')}</small></div>${locationShareStatus(l.shareRide||'never')}<div class="chev">›</div></div></div>`}'''
new_rows = r'''function locationTypeClass(type){return`location-type-${['home','work','business','private'].includes(type)?type:'other'}`}
function locationShareStatus(value){const v=['ask','always'].includes(value)?value:'never',label=v==='ask'?'Rit delen: vraag mij':v==='always'?'Rit delen: altijd tonen':'Rit delen: nooit';return`<span class="location-share-status ${v}" title="${attr(label)}" aria-label="${attr(label)}">↗</span>`}
function locationHasGps(l){return parseNum(l?.lat)!=null&&parseNum(l?.lng)!=null}
function locationLinkStatus(l){const hasAddress=!!String(l?.address||'').trim(),hasGps=locationHasGps(l);let cls='none',label='Adres en GPS ontbreken',icon='A·⌖';if(hasAddress&&hasGps){cls='complete';label='Adres en GPS gekoppeld';icon='A↔⌖'}else if(hasAddress){cls='address-only';label='Adres aanwezig · GPS kan worden aangevuld';icon='A→⌖'}else if(hasGps){cls='gps-only';label='GPS aanwezig · adres kan worden aangevuld';icon='⌖→A'}return`<span class="location-link-status ${cls}" title="${attr(label)}" aria-label="${attr(label)}">${icon}</span>`}
function locationStatusIcons(l){return`<div class="location-status-icons">${locationShareStatus(l.shareRide||'never')}${locationLinkStatus(l)}</div>`}
function locationSwipeRow(l){return`<div class="swipe-row location-swipe-row" data-swipe-kind="location" data-id="${l.id}">${swipeActions('location',l.id)}<div class="swipe-surface location-item location-swipe-surface ${locationTypeClass(l.type)}" data-action="edit-location" data-id="${l.id}"><div class="location-main"><strong>${esc(l.name)}</strong><small>${esc(l.address||coords(l)||'Geen adres/GPS')}</small></div>${locationStatusIcons(l)}<div class="chev">›</div></div></div>`}'''
replace_once(old_rows, new_rows, 'location status icons')

replace_once("destinationTimeWindowHours:Math.min(6,Math.max(.5,num(fd.get('destinationTimeWindowHours'))||2))};save()", "destinationTimeWindowHours:Math.min(6,Math.max(.5,num(fd.get('destinationTimeWindowHours'))||2)),geocoderBaseUrl:String(fd.get('geocoderBaseUrl')||GEOCODER_DEFAULT_BASE).trim()||GEOCODER_DEFAULT_BASE};save()", 'save geocoder setting')
replace_once("<div class=\"range-setting\"><div class=\"range-setting-head\"><div><strong>Tijdvenster bestemmingsvoorstel</strong>", "<div class=\"form-group\"><label>Adresdienst</label><input name=\"geocoderBaseUrl\" value=\"${attr(s.geocoderBaseUrl||GEOCODER_DEFAULT_BASE)}\"><div class=\"hint\">Standaard OpenStreetMap Nominatim. Alleen wijzigen als de adresdienst later wordt vervangen.</div></div><div class=\"range-setting\"><div class=\"range-setting-head\"><div><strong>Tijdvenster bestemmingsvoorstel</strong>", 'geocoder service field')

helpers = r'''function setLocationStatus(message){const el=document.getElementById('locationStatus');if(el)el.textContent=message||''}
function geocoderBaseUrl(){return String(data.settings.geocoderBaseUrl||GEOCODER_DEFAULT_BASE).trim().replace(/\/+$/,'')||GEOCODER_DEFAULT_BASE}
function readGeocodeCache(){try{const x=JSON.parse(localStorage.getItem(GEOCODE_CACHE_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(e){return{}}}
function geocodeCacheGet(key){const c=readGeocodeCache(),row=c[key];if(!row||!row.savedAt||Date.now()-row.savedAt>15552000000)return null;return row.value??null}
function geocodeCachePut(key,value){try{const c=readGeocodeCache();c[key]={savedAt:Date.now(),value};const entries=Object.entries(c).sort((a,b)=>(b[1]?.savedAt||0)-(a[1]?.savedAt||0)).slice(0,100);localStorage.setItem(GEOCODE_CACHE_KEY,JSON.stringify(Object.fromEntries(entries)))}catch(e){console.warn('Geocode-cache kon niet worden opgeslagen',e)}}
function geocodeAddressKey(address){return'address:'+String(address||'').trim().toLowerCase().replace(/\s+/g,' ')}
function geocodeGpsKey(lat,lng){return`gps:${(+lat).toFixed(5)},${(+lng).toFixed(5)}`}
function geocodeWait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function geocodeRequest(path,cacheKey){const cached=geocodeCacheGet(cacheKey);if(cached)return cached;const task=async()=>{const delay=Math.max(0,1100-(Date.now()-geocodeLastAt));if(delay)await geocodeWait(delay);const url=geocoderBaseUrl()+path,response=await fetch(url,{headers:{Accept:'application/json'},referrerPolicy:'strict-origin-when-cross-origin'});geocodeLastAt=Date.now();if(!response.ok)throw new Error(`Adresdienst niet beschikbaar (${response.status}).`);const value=await response.json();geocodeCachePut(cacheKey,value);return value};const p=geocodeQueue.then(task,task);geocodeQueue=p.catch(()=>{});return p}
async function coordinatesForAddress(address){const q=String(address||'').trim(),rows=await geocodeRequest(`/search?format=jsonv2&limit=1&addressdetails=1&accept-language=nl&q=${encodeURIComponent(q)}`,geocodeAddressKey(q)),place=Array.isArray(rows)?rows[0]:null,lat=parseNum(place?.lat),lng=parseNum(place?.lon);if(lat==null||lng==null)throw new Error('Geen GPS-coördinaten gevonden voor dit adres.');return{lat,lng}}
async function addressForCoordinates(lat,lng){const row=await geocodeRequest(`/reverse?format=jsonv2&zoom=18&addressdetails=1&accept-language=nl&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lng)}`,geocodeGpsKey(lat,lng)),address=String(row?.display_name||'').trim();if(!address)throw new Error('Geen adres gevonden voor deze GPS-coördinaten.');return address}
function locationFormGps(form){return{lat:parseNum(form?.elements.lat?.value),lng:parseNum(form?.elements.lng?.value)}}
async function autoFillLocationFromAddress(){const f=document.getElementById('locationForm');if(!f)return false;const address=String(f.elements.address?.value||'').trim(),gps=locationFormGps(f);if(!address||gps.lat!=null||gps.lng!=null)return false;try{setLocationStatus('GPS wordt op basis van het adres opgezocht…');const original=address,result=await coordinatesForAddress(address);if(String(f.elements.address?.value||'').trim()!==original)return false;const current=locationFormGps(f);if(current.lat!=null||current.lng!=null)return false;f.elements.lat.value=result.lat.toFixed(6);f.elements.lng.value=result.lng.toFixed(6);setLocationStatus('GPS aangevuld op basis van het adres. Je kunt de coördinaten altijd verfijnen.');return true}catch(e){setLocationStatus(e.message||'GPS kon niet automatisch worden aangevuld.');return false}}
async function autoFillLocationFromGps(){const f=document.getElementById('locationForm');if(!f)return false;const address=String(f.elements.address?.value||'').trim(),gps=locationFormGps(f);if(address||gps.lat==null||gps.lng==null)return false;try{setLocationStatus('Adres wordt op basis van GPS opgezocht…');const originalLat=gps.lat,originalLng=gps.lng,result=await addressForCoordinates(gps.lat,gps.lng),current=locationFormGps(f);if(String(f.elements.address?.value||'').trim()||current.lat!==originalLat||current.lng!==originalLng)return false;f.elements.address.value=result;setLocationStatus('Adres aangevuld op basis van GPS.');return true}catch(e){setLocationStatus(e.message||'Adres kon niet automatisch worden aangevuld.');return false}}
async function autoCompleteLocationForm(){const f=document.getElementById('locationForm');if(!f)return false;const address=String(f.elements.address?.value||'').trim(),gps=locationFormGps(f);if(address&&gps.lat==null&&gps.lng==null)return autoFillLocationFromAddress();if(!address&&gps.lat!=null&&gps.lng!=null)return autoFillLocationFromGps();return false}
'''
replace_once('function openLocation(id=null,current=false){', helpers + '\nfunction openLocation(id=null,current=false){', 'geocoding helpers')

old_form = r'''function openLocation(id=null,current=false){const l=id?data.locations.find(x=>x.id===id):null,build=g=>openModal(`<div class="modal-head"><h2>${l?'Locatie wijzigen':'Locatie toevoegen'}</h2><button class="close" data-action="close">×</button></div><form id="locationForm" onsubmit="return false"><input type="hidden" name="id" value="${l?.id||''}">${field('Naam','name',l?.name||'')}${field('Adres','address',l?.address||'')}<button type="button" class="btn secondary full" data-action="gps-location">Gebruik huidige GPS</button>${field('Latitude','lat',l?.lat??g?.lat??'','text')}${field('Longitude','lng',l?.lng??g?.lng??'','text')}<div class="form-group"><label>Type</label><select name="type">${['home','work','business','private','other'].map(v=>`<option value="${v}" ${(l?.type||'other')===v?'selected':''}>${typeLabel(v)}</option>`).join('')}</select></div><div class="form-group"><label>Rit delen</label><select name="shareRide"><option value="never" ${(l?.shareRide||'never')==='never'?'selected':''}>Nooit</option><option value="ask" ${l?.shareRide==='ask'?'selected':''}>Vraag mij</option><option value="always" ${l?.shareRide==='always'?'selected':''}>Altijd tonen</option></select><div class="hint">Bij Vraag mij krijg je na vertrek een eenmalige vraag. Bij Altijd tonen blijft Deel rit beschikbaar tijdens de actieve rit.</div></div><div class="hint">Vul minimaal naam, adres of GPS in.</div><div id="locationStatus" class="hint"></div><button type="button" class="btn full" data-action="save-location">Locatie opslaan</button></form>`);if(current)getPosition().then(build).catch(e=>{toast(e.message);build(null)});else build(null)}
async function fillGps(){const f=document.getElementById('locationForm');if(!f)return;const g=await getPosition();f.elements.lat.value=g.lat;f.elements.lng.value=g.lng;toast('GPS ingevuld.')}
function saveLocation(){const f=document.getElementById('locationForm');if(!f)throw new Error('Locatieformulier niet gevonden.');const fd=new FormData(f),id=String(fd.get('id')||uid()),old=data.locations.find(x=>x.id===id),rawName=String(fd.get('name')||'').trim(),address=String(fd.get('address')||'').trim(),lat=parseNum(fd.get('lat')),lng=parseNum(fd.get('lng'));'''
new_form = r'''function openLocation(id=null,current=false){const l=id?data.locations.find(x=>x.id===id):null,build=g=>{openModal(`<div class="modal-head"><h2>${l?'Locatie wijzigen':'Locatie toevoegen'}</h2><button class="close" data-action="close">×</button></div><form id="locationForm" onsubmit="return false"><input type="hidden" name="id" value="${l?.id||''}">${field('Naam','name',l?.name||'')}${field('Adres','address',l?.address||'')}<button type="button" class="btn secondary full" data-action="gps-location">Gebruik huidige GPS</button>${field('Latitude','lat',l?.lat??g?.lat??'','text')}${field('Longitude','lng',l?.lng??g?.lng??'','text')}<div class="location-link-hint"><strong>Adres ↔ GPS</strong><br>Alleen ontbrekende gegevens worden automatisch aangevuld. Bestaande waarden blijven staan. Huidige GPS overschrijft bewust alleen de coördinaten om ze nauwkeuriger te maken.</div><div class="osm-attribution">Adreszoeking via OpenStreetMap Nominatim · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap-bijdragers</a></div><div class="form-group"><label>Type</label><select name="type">${['home','work','business','private','other'].map(v=>`<option value="${v}" ${(l?.type||'other')===v?'selected':''}>${typeLabel(v)}</option>`).join('')}</select></div><div class="form-group"><label>Rit delen</label><select name="shareRide"><option value="never" ${(l?.shareRide||'never')==='never'?'selected':''}>Nooit</option><option value="ask" ${l?.shareRide==='ask'?'selected':''}>Vraag mij</option><option value="always" ${l?.shareRide==='always'?'selected':''}>Altijd tonen</option></select><div class="hint">Bij Vraag mij krijg je na vertrek een eenmalige vraag. Bij Altijd tonen blijft Deel rit beschikbaar tijdens de actieve rit.</div></div><div class="hint">Vul minimaal naam, adres of GPS in.</div><div id="locationStatus" class="hint"></div><button type="button" class="btn full" data-action="save-location">Locatie opslaan</button></form>`);setTimeout(()=>autoCompleteLocationForm(),0)};if(current)getPosition().then(build).catch(e=>{toast(e.message);build(null)});else build(null)}
async function fillGps(){const f=document.getElementById('locationForm');if(!f)return;const g=await getPosition();f.elements.lat.value=(+g.lat).toFixed(6);f.elements.lng.value=(+g.lng).toFixed(6);setLocationStatus('GPS verfijnd met je huidige locatie.');await autoFillLocationFromGps();toast('GPS verfijnd met huidige locatie.')}
async function saveLocation(){const f=document.getElementById('locationForm');if(!f)throw new Error('Locatieformulier niet gevonden.');await autoCompleteLocationForm();const fd=new FormData(f),id=String(fd.get('id')||uid()),old=data.locations.find(x=>x.id===id),rawName=String(fd.get('name')||'').trim(),address=String(fd.get('address')||'').trim(),lat=parseNum(fd.get('lat')),lng=parseNum(fd.get('lng'));'''
replace_once(old_form, new_form, 'location form geocoding')

index.write_text(text, encoding='utf-8')

sw = Path('service-worker.js')
sw_text = sw.read_text(encoding='utf-8')
if sw_text.count("kmreg-shell-0.27.8") != 1:
    raise SystemExit('service worker: expected cache 0.27.8 once')
sw.write_text(sw_text.replace("kmreg-shell-0.27.8", "kmreg-shell-0.27.9", 1), encoding='utf-8')

script = text.split('<script>',1)[1].rsplit('</script>',1)[0]
Path('/tmp/kmreg-app.js').write_text(script, encoding='utf-8')
